### ISSUE TITLE
Value of "scale" is undefined in image-drawing.js

### ISSUE THREAD

**Issue by vinnyjth** [collinhover/impactplusplus#1]
In Image-drawing.js on line 129 x and y are both divided by "scale", but I can't seem to find where you define scale. I would issue a pull request, but with trial and error I have been unable to find what the value of scale should be. 

I tried changing scale to "this.scale" which ran without errors, but gave very odd results when trying to view any images.

**Comment by collinhover** [comment]
Thanks for opening the issue! I'm fairly certain that r4 fixes this, as I've run into the same problems you mentioned. I'll leave the issue open for now and we can revisit once I push r4 later this week.

**Comment by collinhover** [comment]
In the meantime, you can edit the following line:

https://github.com/collinhover/impactplusplus/blob/master/lib/plusplus/core/image-drawing.js#L99

and prepend "var scale =" to it. That said, there are still other fixes to image-drawing coming.

**Comment by vinnyjth** [comment]
I performed that change, and a basic level ran without errors, except for a few graphic issues: 

My 16_16 sprite-sheet only worked if I defined it as an 8_8 tile sheet, I couldn't seem to get the animations to work properly, but they may be an issue on my end. 

All tiles on my tile-sheet were wrong; tiles that were ordinarily grass showed up as dirt for example. 

I can't wait to see r4! You should upload your current changes as a development branch so I can take a look.

**Comment by collinhover** [comment]
In reply to the sprite sheet, are you saying 16 x 16 is the total width x height of the image file, or that the tiles are 16 x 16? If the tiles are 8 x 8, then "new ig.AnimationSheet( "path.png", 8, 8 )" is correct, as the 2nd and 3rd parameters are actually the tile size, not the sheet size. In the Impact source code it is named in such a way as to suggest otherwise, which is confusing. Would that potentially fix your tiles showing up incorrectly?

**Comment by vinnyjth** [comment]
The size of the actual tiles on the tile sheet are 16*16. The code works in other settings, just doesn't seem to work here.

**Comment by collinhover** [comment]
Do you have the code in question available anywhere? It'd help if I could take a look, in case there is some bug I missed.

**Comment by collinhover** [comment]
r4 is up, assuming this is fixed. Reopen if not and we'll figure it out!
