### ISSUE TITLE
Spawner Bounds

### ISSUE THREAD

**Issue by Mmarzex** [collinhover/impactplusplus#100]
This may just be me being unclear of the documentation but if I set the bound.width and bound.height of the game width and height shouldn't the spawner spawn anywhere in the bounds? It keeps only spawning in one spot.

**Comment by collinhover** [comment]
I don't think I understand the question. The `bounds` property of entities is no longer used unless you opt into it, and most calculations ignore it at this point. If you want to change the size of the spawning area, set the spawner's `size.x/y`.

**Comment by collinhover** [comment]
In fact, thanks for point this out. I've removed all instances and usages of bounds as they were a remnant of r4 that never got fully removed, despite doing nothing.
