### ISSUE TITLE
Changing Animation

### ISSUE THREAD

**Issue by Mmarzex** [collinhover/impactplusplus#104]
This may be a stupid question but if I set different states in an entity's animationSettings. How do I change currentAnim to one of them?

**Comment by collinhover** [comment]
If your entity extends ig.Character, `updateCurrentAnim` has some automatic animation handling. If it doesn't handle all the states you need, you can easily override it.

You can also set the `animInit` property to the name of the animation you want the entity to start with, but characters will usually change this on their first update.

**Comment by Mmarzex** [comment]
Alright, I'll try some of those options. I'm not sure that will work though, the issue is my sprite sheet is basically a bunch of different items for the game I'm working on, what I ideally want to do is every time an item is spawned it loads a different frame, can I do that in the init function?

**Comment by collinhover** [comment]
Assuming each frame is the same size, which impactjs requires by default, yes. Within each item class, set the `animInit` as I mentioned above. If you have only one item class, override the `resetExtras` method and do it there based on what item it is at that spawn.

**Comment by Mmarzex** [comment]
I just have one EntityClass for each category of items. Essentially it is three or four categories which are each different entities but multiples of the entity are spawned by different spawners so each category has 10+ different images that it could look like. I guess I don't really know how to do that so that when it it is spawned it changes to a different image.

**Comment by Mmarzex** [comment]
Also my item is just an EntityExtended.

**Comment by collinhover** [comment]
In that case do both of what I suggested in my last reply.
