### ISSUE TITLE
ui-meter + ejecta could not work only with real device

### ISSUE THREAD

**Issue by parazox** [collinhover/impactplusplus#115]
I built supercollider example with ejecta.  it works well in simulator. but in real ios device ui-meter setValue function does not work.
meter could not filled.

![2014-01-10 23 11 46](https://f.cloud.github.com/assets/818934/1893074/34bbbf7c-7a6a-11e3-8738-c7580bb3f1b5.png)

**Comment by collinhover** [comment]
My guess is that the setValue and/or value properties are used by something else overriding the ui-meter. Can you run a search and replace on all instances of the property `value` and method `setValue` in the lib/game/entities/player.js and lib/plusplus/ui/ui-meter.js files? Rename them something such as `meterValue` and `setMeterValue`. Does this fix the issue?

**Comment by parazox** [comment]
I had rename setValue to meterValue but got same result.

On the other hand i tried some setting on ui-meter.js
and found out that barSize.x causes this.

by default 
this.barSize.x is 32

I changed this.barSize.x to 33
and this solved the problem.

I do not know why be so... 
might be bug in Ejecta

**Comment by collinhover** [comment]
Thank you for checking. I suspect there is something else at work, but for now I'm changing the name of the value property as I noted above as well as fiddling with the bar size. Perhaps there is a rounding/sub-pixel issue on the actual iOS device.
