### ISSUE TITLE
spawnAndMoveTo Question

### ISSUE THREAD

**Issue by racingcow** [collinhover/impactplusplus#116]
Hello,

I have created a generic `SpawnerCharacterLibraried` module, very similar to the one used in the supercollider demo, to use to generically create various spawners in Weltmeister. I have it set up to spawn at a void entity at a location underneath it. Everything works fine, and the spawner creates entities of the specified type at the void entity as it should.

Now, after they spawn, I want the entities walk from the spawn point to another void entity. Here is a screenshot of what I have in the editor...

![image](https://f.cloud.github.com/assets/1176637/1893197/bb3798ea-7a75-11e3-8a90-fad85c344ff8.png)

...and here are the properties set on the `spawner1` spawner in the editor...

``` JavaScript
{
    name: spawner1,
    spawnTarget.1: spawnpoint1,
    spawnTarget.2: defendpoint,
    spawningEntity: EntityBeforeLight,
    spawnCountMax: 5,
    duration: 20,
    animSheetPath: enemy-factory.png,
    spawnAndMoveTo: true,
    spawnAtFirstTarget: true
}
```

The entities all spawn, but don't move to the second target afterward. When debugging, I noticed that they start wandering immediately, which seemed to prevent them from moving to the second target (`canWanderX` / `canWanderY` were set on the spawned entities). To try and override that, I added the following settings to `spawner1`...

``` JavaScript
{
    spawnSettings: {
        canWanderX: false,
        canWanderY: false
    }
}
```

Still no luck. The entities would spawn at the first target, but then stay there. After stepping through the code some more, I verified that the creature was no longer trying to wander, and `spawner.spawnNext` is definitely calling `moveTo` and passing in the entities in the `targets` map. `entity.moveTo` sets the entity's `movingTo` property to the first target in the map, and returns `true`, making the entity move to it.

After that, however, it seems to stop without trying to move to the second target, and I'm not sure why.

Is there something I need to do differently to get the entity to move the second target after being spawned?

Thanks in advance for any help that you might be able to give and, as always, thanks for the great library!

**Comment by collinhover** [comment]
In the spawnSettings, set the `preyName` property to the name of the entity you want the creatures to move to after spawning. Make sure the creatures either have infinite reaction and search distance or they spawn within their search distance range to the final move to target. Creatures manage their own movement via wander, prey, and predator, so trying to use move to directly doesn't work so well (yet). Spawners also don't account for creatures in the spawn and move to setup (yet), as it was originally intended for non dynamic entities when I added it.

**Comment by racingcow** [comment]
Setting the `preyName` works great. They now move to the entity to which it is set. Thanks, @collinhover!
