### ISSUE TITLE
Disable transition fade on game start?

### ISSUE THREAD

**Issue by Pattentrick** [collinhover/impactplusplus#118]
Hi @collinhover!

Is there a way to disable the transition fade, that gets displayed directly after the game has finished loading? I already disabled it between levels in my config like this:

``` javascript```
// show transition between levels
TRANSITION_LEVELS: false,
```

But i have no clue how i do it once the game has finished loading.

Thanks for any help and information on this!

**Comment by collinhover** [comment]
The initial fade is handled by the core/loader, so you'll need to check there. I don't think I considered disabling that fade, so you may need to extend it with your own loader.

**Comment by Pattentrick** [comment]
Thanks for the info @collinhover! I just overwrote the run method with my own code, works like a charm!
