### ISSUE TITLE
Game crashes on dynamic light with pixel perfect scaling

### ISSUE THREAD

**Issue by Pattentrick** [collinhover/impactplusplus#128]
Hi @collinhover,

i just noticed that the game crashes if i use dynamic lights/shadows and pixel perfect scaling. You can reproduce this issue when you set `pixelPerfect: true` to the fourth light on the `lighting.js` at the SUPERCOLLIDER demo.

I made a picture of what is happening on a testing level with just one light:

![crash](https://f.cloud.github.com/assets/1792087/2118789/2179a578-9121-11e3-83a7-bb76152ac7ca.png)

Here is the callstack fro the SUPERCOLLIDER demo:

``` javascript```
Uncaught TypeError: Cannot read property 'data' of null image.js:227
ig.Image.inject.resize image.js:227
ig.Image.inject.draw image.js:282
ig.EntityLight.ig.global.EntityLight.ig.EntityExtended.extend.draw light.js:942
ig.Layer.ig.Class.extend.draw layer.js:741
ig.GameExtended.ig.Game.extend.draw game.js:2235
ig.GameExtended.inject.draw entities-panel.js:19
(anonymous function) impact.js:480
ig.GameExtended.inject.draw graph-panel.js:17
(anonymous function) impact.js:480
ig.Game.ig.Class.extend.run game.js:171
ig.System.inject.run plusplus.js:229
ig.System.inject.run menu.js:16
(anonymous function) impact.js:480
animate impact.js:436

Uncaught TypeMismatchError: The type of an object was incompatible with the expected type of the parameter associated to the object. image.js:233
ig.Image.inject.resize image.js:233
ig.Image.inject.draw image.js:282
ig.EntityLight.ig.global.EntityLight.ig.EntityExtended.extend.draw light.js:942
ig.Layer.ig.Class.extend.draw layer.js:741
ig.GameExtended.ig.Game.extend.draw game.js:2235
ig.GameExtended.inject.draw entities-panel.js:19
(anonymous function) impact.js:480
ig.GameExtended.inject.draw graph-panel.js:17
(anonymous function) impact.js:480
ig.Game.ig.Class.extend.run game.js:171
ig.System.inject.run plusplus.js:229
ig.System.inject.run menu.js:16
(anonymous function) impact.js:480
animate impact.js:436
```

Is this a bug, or is a light with pixel perfect scaling not allowed to cast shadows?

**Comment by Pattentrick** [comment]
Update: This only occurs with `castsShadowsMovable`, static map shadows are fine.

**Comment by collinhover** [comment]
This looks like a bug indeed. Can you see if putting an existence check in the image's resize method fixes it?

That said, I'd recommend never using dynamic shadows with pixel perfect lights. There is no way you'll get more than maybe 2-5 fps, as it has to be scaled per pixel on the cpu constantly using the canvas `getImageData` methods. If we could offload it to the gpu, it'd be another story entirely, but no dice as long as impactjs is strictly canvas 2d.

**Comment by Pattentrick** [comment]
Not sure about the existence check. I checked the `scaledPixels` and the `origPixels`  around here with no results:

https://github.com/collinhover/impactplusplus/blob/dev/lib/plusplus/core/image.js#L253

I am working on the dynamic lighting tutorial right know. I will note there that movable shadows won't work together with perfect pixel lights, if that is ok with you. It's really a pity though, that impactjs is strictly canvas 2D.

**Comment by aroth** [comment]
The real pity of ImpactJS is the lack of texture memory management for high
resolution games on iOS devices, but I'm not in my right mind at the
moment. Again, great work guys. Your pace reminds me of..... myself about 2
months ago. Ignore this diatribe. It'll be part of my story in a couple
months. I'll post a video of what I've created shortly. Again, I know this
doesn't belong in this thread, but stranger things happen.

**Comment by Pattentrick** [comment]
@collinhover Do you think it's a good idea, and possible without rewriting much of the code, to alter the lighting entity in such a way that it doesn't cast any shadows on other entities, if it's a pixel perfect light? I could give it a try within the next couple of days and sent a pull request if i succeed.

@aroth Looking forward to that video ;-)

**Comment by collinhover** [comment]
@Pattentrick yes, we'd likely just need a check in the light's shadow casting method.

**Comment by Pattentrick** [comment]
@collinhover Ok, i will give it a try then later on.
