### ISSUE TITLE
Camera shake: Third Parameter?

### ISSUE THREAD

**Issue by Pattentrick** [collinhover/impactplusplus#132]
Working on the camera tutorial right now. What's the idea behind the third parameter (fn) of the shake method? Is this for defining an own multiplier for the "shakiness"?

**Comment by aroth** [comment]
Looks like you can pass in a custom shake function, otherwise it defaults to: 

```
var value = this.shakeFunction ? this.shakeFunction() : ( this.shakeStrength * Math.pow(deltaPct, 2) );
```

**Comment by aroth** [comment]
More specifically:

in #shake: this.shakeFunction = fn || this.shakeFunction;
in #updateShake: var value = this.shakeFunction ? this.shakeFunction() : ( this.shakeStrength \* Math.pow(deltaPct, 2) );

**Comment by Pattentrick** [comment]
@aroth Thanks for explaining. I will experiment with that. Glad to know that you are still around here.

**Comment by collinhover** [comment]
@aroth is correct =)
