### ISSUE TITLE
How to focus an Character Entity?

### ISSUE THREAD

**Issue by tobiaslins** [collinhover/impactplusplus#134]
Hello!

I got two entitys
1. Player which is controlable
2. Character, which is just on the map

Now i want to check if the character got clicked by the player

I found this snipped in a forum: 

```
update: function() {
    if (ig.input.pressed('leftButton') && this.inFocus()) {
        ig.log('clicked');
    }
},

inFocus: function() {
    return (
       (this.pos.x <= (ig.input.mouse.x + ig.game.screen.x)) &&
       ((ig.input.mouse.x + ig.game.screen.x) <= this.pos.x + this.size.x) &&
       (this.pos.y <= (ig.input.mouse.y + ig.game.screen.y)) &&
       ((ig.input.mouse.y + ig.game.screen.y) <= this.pos.y + this.size.y)
    );
 }
```

It is working with the update method, but the problem is, when "update" gets overwritten, the character is not drawn on the canvas.

i tried to use handleInput but it won't work

thank you for your help

**Comment by Pattentrick** [comment]
You have to call `this.parent()` on your update method:

``` javascript```
update: function() {

    this.parent();

    if (ig.input.pressed('leftButton') && this.inFocus()) {
        ig.log('clicked');
    }

}
```

**Comment by tobiaslins** [comment]
oh thanks its working now!

**Comment by Pattentrick** [comment]
You're welcome!
