### ISSUE TITLE
Let Protectile fly on function

### ISSUE THREAD

**Issue by tobiaslins** [collinhover/impactplusplus#135]
Is there a way to let a        'plusplus.abstractities.projectile'
fly on a sin(x) or something like that?

if yes, which function do i need to overwrite?

overwriting update isn't working!

Sorry, im new to impact++

thanks for your help

**Comment by Pattentrick** [comment]
Hi @tlins,

I guess you already learned about the basics of the projectile abstract, and you took a look at the example from the player tutorial that @collinhover made?

https://github.com/collinhover/impactplusplus/issues/123

As far as I know, projectiles fly in a straight line based upon `offsetVelX` / `offsetVelY`, or `offsetAccelX` / `offsetAccelY` defined at the `ig.AbilityShoot` class. You mentioned `sin(x)`, so you want your projectile moving up and down like in a sine wave?

I don't think that this is something that ++ can do by default. But you could overwrite the update method of the projectile (don't forget to call `this.parent()`) and alter the `accel.y` property every X seconds (use a ig.Timer for that) so the projectile goes up and down while it moves on the x axis. Use a flag like `isMovingUp: true` outside your update method to keep track of the current state, so you know if you should increment or decrement the `accel.y` property.

There may be a much better solution to this. But that's how I would do it right know.

**Comment by collinhover** [comment]
@Pattentrick is correct, there is nothing built into projectiles or particles to handle movement other than in the direction of acceleration. @tlins you'll want to extend `ig.Projectile` and then in your custom projectile override the `updateVelocity` method. This is what it does now: https://github.com/collinhover/impactplusplus/blob/master/lib/plusplus/core/entity.js#L5039

Good luck =)
