### ISSUE TITLE
Directional Lights / ShadowImpact

### ISSUE THREAD

**Issue by Falconerd** [collinhover/impactplusplus#150]
Hey, was wondering if there is currently a way to make lights directional, as far as I can tell they are only omnidirectional unles you block parts of the lights and use `opaque` and `diffuse`. I did try loading the ShadowImpact plugin, but that just froze my game and I'm not sure why. I did check out ShadowImpact's issues and there is indeed an open issue about it. However, the author hasn't replied in 6 months so I'm going to assume he's not currently active on the project. (https://github.com/fourty2/ShadowImpact/issues/4)

**Comment by collinhover** [comment]
Hi @Archadian, lights are not directional at the moment and there are no options to do so. Sorry!
