### ISSUE TITLE
Trying to integrate it into my existing code

### ISSUE THREAD

**Issue by ChrisCorrigan** [collinhover/impactplusplus#16]
Hi Collin, please see my latest reply here:

http://impactjs.com/forums/code/impact-library-75-additions/page/1#post24580

Re: I've worked my way through step 1 and 2 of the getting started guide, but I'm having issues with the entities not moving. 

thanks
Chris

**Comment by collinhover** [comment]
Check out the reply in the same thread. Did that fix your issue?

**Comment by collinhover** [comment]
Hey Chris, I've just added a Jump N' Run demo to the examples directory. Check it out, I think it will solve all of your confusion!

**Comment by ChrisCorrigan** [comment]
Thats great! That will definitely help a lot.

**Comment by ChrisCorrigan** [comment]
Hi Colin - please see my latest reply here if have time 
http://impactjs.com/forums/code/impact-library-75-additions/page/1#post24674

**Comment by collinhover** [comment]
FPS Issue should be solved.

**Comment by ChrisCorrigan** [comment]
Thanks! I just send you a private message through the impact site btw.

**Comment by ChrisCorrigan** [comment]
er its not a priv msg in github, but it should have emailed you my msg.
