### ISSUE TITLE
Create a time machine...

### ISSUE THREAD

**Issue by Zetaphor** [collinhover/impactplusplus#160]
...and go back in time and give this to me 2 years ago when I had to write most of this functionality myself.

Seriously though, thanks to collinhover and everyone else who has contributed to this project, this is going to save me _hours_ of additional work!

**Comment by Pattentrick** [comment]
Time machines are not supported by ++ right know. I once planned to add this to ++ as I started to use this cool library. However I had problems with a very confusing time paradox at the beginning that I could not work around. Maybe I'll try again in the future, when a new JavaScript API for time travelling is supported in all major browsers ;-)

**Comment by collinhover** [comment]
LOL. Cheers :-) hope you come back and say the same after you've used it!
