### ISSUE TITLE
Player Multi Entity 

### ISSUE THREAD

**Issue by CarlosX** [collinhover/impactplusplus#162]
anyone have any idea how to create this entity

![player combine](https://cloud.githubusercontent.com/assets/566906/3124738/7b091d16-e780-11e3-8713-15eb3464a0a7.png)

![mh00000](https://cloud.githubusercontent.com/assets/566906/3124741/81a4b216-e780-11e3-953d-60c21e460dd3.png)
![mb00000](https://cloud.githubusercontent.com/assets/566906/3124740/8093e6d0-e780-11e3-96ba-cf3d2e256427.png)
![armor](https://cloud.githubusercontent.com/assets/566906/3124739/7f12f90e-e780-11e3-8642-ae7c9d93cc42.png)

**Comment by Pattentrick** [comment]
Can you be more specific? What is your goal? You can make an animation sheet that will combine all states seen at your post and swap the animations as needed with only one entity. Or you could use multiple entities (head, body, machine) and try to "synchronize them". It's hard to give you an advice without more information about what you are trying to do.

**Comment by CarlosX** [comment]
is like a rpg .. you equip a hat and head change..
but I want to know if there is any way to do this without creating multiple entities
something like this
http://impactjs.com/forums/code/layered-animation-sheet

**Comment by collinhover** [comment]
At the moment ++ does not support multi part entities. You can certainly do it without creating multiple entities. Without testing it myself, I'd guess you'd need to modify the update animation and draw methods of an entity to call themselves once for each part and swap out the animation sheet, anims, size, and offset.
