### ISSUE TITLE
yeoman generator

### ISSUE THREAD

**Issue by racingcow** [collinhover/impactplusplus#165]
Hello,

I made a [yeoman generator](https://github.com/racingcow/generator-impactplusplus) that will quickly scaffold impact++ games. It will generate either a blank game, or the jumpnrun or supercollider examples. It will also spin up a livereload-style server to make things a bit easier to debug.

While this is part shameless plug :stuck_out_tongue_winking_eye:, I thought it might be useful when people need to spin up a new project to demonstrate a new feature or issue submission for impact++.

I'd definitely appreciate any feedback you might have on it. Feel free to submit any issues that you find!

Thanks again for the always awesome impact++ library.

Some relevant links...
-  GitHub repo - https://github.com/racingcow/generator-impactplusplus
-  npm package page - https://www.npmjs.org/package/generator-impactplusplus
-  Point of Impact page - http://www.pointofimpactjs.com/resources/view/24/generator-impactplusplus

![image](https://cloud.githubusercontent.com/assets/1176637/3295358/f713cd84-f5bd-11e3-8258-10ee1793a66a.png)

**Comment by collinhover** [comment]
@racingcow this is awesome, nice work! We need to get this plugged into the front page of the github-pages.

**Comment by Pattentrick** [comment]
@racingcow Looks awesome! Glad to hear that you are still playing around with ++.

**Comment by collinhover** [comment]
Thanks again @racingcow, I've added several links into the main readme. You rock!
