### ISSUE TITLE
Work with TWEENS tutoral

### ISSUE THREAD

**Issue by z4kk** [collinhover/impactplusplus#174]
Hi?
Where I can find **tutorial** or examples with TWEENS? 
Is Impact++ Tween **chainable**?

**Comment by collinhover** [comment]
@z4kk wow for some reason I was never notified of this issue, sorry! There are no examples of tweens in Impact++, but it is basically the TWEEN.JS library wrapped: https://github.com/sole/tween.js/

There are some built in tweening functions that you can use:
Entity.tween - https://github.com/collinhover/impactplusplus/blob/master/lib/plusplus/core/entity.js#L3396
Entity.moveTo - https://github.com/collinhover/impactplusplus/blob/master/lib/plusplus/core/entity.js#L3505
Entity.fadeTo - https://github.com/collinhover/impactplusplus/blob/master/lib/plusplus/core/entity.js#L3304
Entity.fadeToDeath - https://github.com/collinhover/impactplusplus/blob/master/lib/plusplus/core/entity.js#L3364
Entity.tweenEnd - https://github.com/collinhover/impactplusplus/blob/master/lib/plusplus/core/entity.js#L3447

At the moment the whole tweening system is not chainable and is very primitive.
