### ISSUE TITLE
Question about EntityPlayer location.

### ISSUE THREAD

**Issue by navopw** [collinhover/impactplusplus#183]
Everytime i start the game the player is located at the top-left corner of the map.

Someone knows where the problem is?

Screenshot:
Editor: http://puu.sh/kw1ol/069f3910e3.png
Ingame: http://puu.sh/kw1py/02f60a1151.png

Greetings

Navo

**Comment by collinhover** [comment]
@nxxv0 are all those blocks behind the character colliders?

**Comment by navopw** [comment]
Nevermind, i found my problem.

I changed something in the impactplusplus code directly, so i broke the player spawning :)
