### ISSUE TITLE
Merging with Impact

### ISSUE THREAD

**Issue by Protonull** [collinhover/impactplusplus#185]
[ImpactJS](https://github.com/phoboslab/Impact) was made free and open source on the [3rd May 2018](https://impactjs.com/blog/2018/05/impact-is-now-free-open-source) under the same MIT license that Impact++ has. Just wondering whether there's any intention and or motivation to begin merging the good work done with Impact++ into ImpactJS itself?

**Comment by collinhover** [comment]
The short answer is no. Impact++ is no longer under active development and the ImpactJS creator has always taken the stance that these two will remain separate.

Thanks for asking!
