### ISSUE TITLE
current anim not being set to jump and fall

### ISSUE THREAD

**Issue by raygerrard** [collinhover/impactplusplus#2]
please see fiddle: http://jsfiddle.net/gbMCQ/

line 1588 of character.js, this.ungrounded is never true, the current animated is never set to jump or fall when a jump occurs.

**Comment by collinhover** [comment]
Working on it now, thanks for catching this! More soon.

**Comment by collinhover** [comment]
Looks like the problem was a dead property I forgot to clean up when refactoring. Should be working on dev branch, which I'll merge into master once I've got issue #4 fixed. Reopen if not!
