### ISSUE TITLE
Possibility to set margins on the canvas?

### ISSUE THREAD

**Issue by nakanaa** [collinhover/impactplusplus#37]
I wanted my canvas to be fullscreen (GAME_WIDTH_PCT = 1 & GAME_WIDTH_PCT = 1) but leave space for a 200px sidebar. For it, I added these to config-user.js:

``` javascript
"GAME_WIDTH_MARGIN": 200,
"GAME_HEIGHT_MARGIN": 0,
```

and edited core/game.js resize function:

``` javascript
var width = _c.GAME_WIDTH_PCT ? ig.global.innerWidth * _c.GAME_WIDTH_PCT - _c.GAME_WIDTH_MARGIN : _c.GAME_WIDTH;
var height = _c.GAME_HEIGHT_PCT ? ig.global.innerHeight * _c.GAME_HEIGHT_PCT - _c.GAME_HEIGHT_MARGIN : _c.GAME_HEIGHT;
```

I think this would be a good addition to Impact++ itself. Didn't make a pull request at least yet because I wasn't sure if you'd want this in.

**Comment by collinhover** [comment]
I wouldn't mind having this functionality, thanks for submitting the idea! However, it looks as if your margin setup only affects the game when the screen size is set by a percent of the window size, and it only puts the margin on the right and/or bottom. We'd need to add config options to set the margins on any side and it seems like we'd also need to modify the CSS of the canvas?

**Comment by collinhover** [comment]
Closing for now due to inactivity. If you get the feature worked out, please submit a pull request!
