### ISSUE TITLE
EntityPlayer Regen properties are not persisting across player respawns

### ISSUE THREAD

**Issue by cnohara** [collinhover/impactplusplus#42]
When an EntityPlayer dies and is respawned at a Checkpoint, the Regen properties are no longer in effect.  The same effect is seen when Regen properties are set on a Player, then a new level is loaded via ig.loadLevelDeferred().  Once the new level is loaded, the regen is no longer active.

**Comment by collinhover** [comment]
Assuming this fixed it, let me know if not!

**Comment by martypenner** [comment]
It seems that the player's energy is still not regenerating after the level load; it's just reset to the original, as you've mentioned. Using abilities with energy costs simply depletes the player's energy.

**Comment by collinhover** [comment]
@encryptoknight just tested on my end and regeneration is working through multiple level loads. By default "regen" is set to false and "regenRateEnergy" is 0. Can you give me more information from your setup that might be causing the issue?

**Comment by collinhover** [comment]
@cnohara posted that this issue may still be present only when spawning the player via the game's `spawnEntity` method, as opposed to placing the player in a level in weltmeister. Is this your situation @encryptoknight?

**Comment by martypenner** [comment]
I'm going to try moving my player entity to another sandboxed game to better debug this. I'll see if I can get to it tonight.

**Comment by martypenner** [comment]
Boy, I feel a little silly now. I had a forgotten player entity in my second level, so on level load, it was getting used instead of my previous entity.

However, it seems I don't quite understand the checkpoint system, as the player isn't spawned at all in the second level. I've got an `EntityLevelchange` in the first level with the `playerSpawnerName` property set to the name of the `EntityCheckpoint` in the second level. I've moved my player entity into a new, extremely simply test game that has no fancy stuff; just a main.js that mimics your jump'n'run game, my 2 levels, and my player entity. Any idea what I might be doing incorrectly?

**Comment by collinhover** [comment]
@encryptoknight by default, the player entity is persistent, and the way the game currently handles persistent entities is by storing the first instance of the persistent entity it encounters, and when the current level tries to spawn a new instance (i.e. you've placed it in the level via weltmeister or just make a spawn call), it replaces the new instance with the original instance. However, any settings passed to the spawn call will be merged into the original instance just as usual. So currently, you will need to place a player entity in each level to get the player to spawn properly.

Do you think there might be a better (or more intuitive) way to handle persistent entities and/or the player entity?

**Comment by collinhover** [comment]
Alright, just ran tests with the following setup:
- player entity spawned in test 1 with weltmeister placement
- player entity spawned in test 2 by inserting a spawn call at the end of the game's buildLevel method

In both tests:
- player has 10 energy max and a regen rate of 0.1 energy per update
- player has an ability that uses 4 energy per use
- player uses the ability at random
- player dies repeatedly with less than max energy
- player changes levels repeatedly

I ran this set of 2 tests on both the jump n' run example and my own game, and in neither case could I get the player entity regeneration to break. Can someone upload or send me a test case (minus the impact engine files) where the regeneration breaks?

**Comment by cnohara** [comment]
I see, thank you for testing this out.  Perhaps I am implementing it wrong.  I will try to prepare a new project to see if I can recreate the problem and then if so, send it to you.  To confirm, may I ask how to properly set up abilities that have energy costs along with regen?  I'm probably doing it wrong!

**Comment by collinhover** [comment]
I updated the jump n run demo to include both:

Ability cost 
https://github.com/collinhover/impactplusplus/blob/dev/examples/jumpnrun/lib/game/abilities/grenade-launcher.js#L32

Regen
https://github.com/collinhover/impactplusplus/blob/dev/examples/jumpnrun/lib/game/entities/player.js#L166

**Comment by cnohara** [comment]
Hi, I checked over my code and I was doing the same as the sample code.  However, I decided to try it from scratch again, and all is well.  I think you can consider this closed!  Thank you!

**Comment by collinhover** [comment]
Thanks for double checking! I do want to make sure we're bug free so I appreciate the reports :-)

**Comment by martypenner** [comment]
I tried putting my player entity (plus dependencies) into your jump'n'run demo, and regen works _some_ of the time. Bizarre. I think it has something to do with my weapon swapping. I'll continue stripping down my player entity, but I'm almost certain it's a problem on my end. Thanks for all the input.

**Comment by collinhover** [comment]
@encryptoknight keep me updated please :-)

**Comment by martypenner** [comment]
@collinhover Will do.
