### ISSUE TITLE
Examples Needed for Advanced Features

### ISSUE THREAD

**Issue by collinhover** [collinhover/impactplusplus#47]
If there is an advanced feature that does not yet have an example in either `examples/jumpnrun` or `examples/supercollider`, and you feel it is difficult to understand, please reply here and let me know. I've recently added a Impact++ SUPER COLLIDER! demo, which uses almost every single feature in the library, but it may not catch everything.

**Please submit your requests as lists (even in the case of a single)**
- Pathfinding (done)
- Pathfinding Maps (done)
- Creature Prey / Predator (done)
- Doors (done)
- Checkpoints and Persistent Player (done)
- UI Element (done)

**Comment by racingcow** [comment]
Here is my list so far, just to show what I am using. You've covered all of it in your list above, but as I add more into my game and need/can't find examples, I'll come back and edit this to add more.
- Pathfinding
- Pathfinding maps
- Explanation of intent of existing "types" and how/when to use them. i.e. `ig.Ability.TYPE.SPAMMABLE`

**Comment by mahgo** [comment]
- UIElement: Basic Dynamic HUDs, such as showing details of a selected entity

**Comment by arakash92** [comment]
How do I use pathfinding? I have no idea :confused: 

I'd love to see either a new section in the documentation for 'use cases' or short tutorials for common things. If I knew more about impact++ I would love to write some.

**Comment by arakash92** [comment]
So, I got pathfinding to work both using simple and complex.

The complex one is OK, my NPC is able to find me by jumping up 1 block etc.

But if I have a map like this (in a sidescrolling game):

![screenshot](http://new.tinygrab.com/55cc6b41da252ed5055bc16830cfb9a6851afa4702.png)

He just attempts the same path over and over and tries to jump like crazy.
Of course.. he never succeeds :P

Is this a bug or is this simply too complex a behavior for the pathfinding?

Is this something the pathfinding system is unable to do?

**Comment by collinhover** [comment]
Keep in mind pathfinding is just finding the most efficient path from A to B. Based on your image, you are trying to get it to jump to the right and then to the left, which feels more like AI than pathfinding. This is why I made pathfinding maps, so you can draw general areas that pathfinding will be more likely to use. Check out #46 and the creatures level of the super collider example. The short version is:
1. Make a new layer on your level, calling pathfinding
2. Use the pathfinding tileset that comes with Impact++ (whichever size fits your game)
3. Draw bright green tiles in the locations that you really want the pathfinding to use

**Comment by collinhover** [comment]
This is what I'd expect, using pathfinding maps, where green squares are the pathfinding map tiles. You may have to tweak it a bit to get the desired result.

![pathfindingmaps](https://f.cloud.github.com/assets/1005377/1239756/36520e96-2a00-11e3-861e-f1cc0ea14718.png)

**Comment by arakash92** [comment]
It seems to me though that the Character class does more than pathfinding in that it causes the character to jump. I guess I'll have to override some of the methods and re-implement all of the AI.

Anyway, I'll try using the pathfinding maps in that way. Thanks again. You even drew up an image!. :+1:

**Comment by collinhover** [comment]
To be clear, the Character class does not do pathfinding itself, it does path following. The basic process is: 1) the character needs to move to a location or entity, 2) it makes a request to the pathfinding utility, 3) the pathfinding utility tries to find a path within an optional distance and optionally avoiding other entities, 4) the character gets the path and tries its best to move to each node in turn by moving, jumping, climbing, checking for dangerous areas, etc. If you override the basic path following in the character, you could try to make better guesses on how to get to the next node in the path, but that seems specific to each game. Not to mention, you'd still be working with the same path as you have right now until you change the way paths are found. Hope that helps!

**Comment by arakash92** [comment]
I tried painting in some light green tiles on the pathfinding layer but it didn't make much difference.

The path is wrong basically. the pathfinding utility returns a path which is impossible to follow. Unless my character can fly, which he can't.

My character needs to be able to say "give me a new path different than the one I have now" to the pathfinding utility.

So, I would need to mess with how paths are created, right?

What could work though is a way for the character class to keep a memory of paths attempted and if it's unable to get to a certain node (through a configurable timer or something) it would mark that path as 'impossible' and request a NEW, different path.

The paths that do work, would be saved on the character class (statically) for use with all entities that derive from that class. (because some entities might jump higher than others etc)

With such a system, a character can actually 'learn' over time which paths work and which don't.

**Comment by arakash92** [comment]
Actually, I was able to get him to jump up the blocks! ;D

Here's how the pathfinding layer looks like now:
![pathfinding layer](http://new.tinygrab.com/55cc6b41daff5b9b6c0a70bdebe96d491022da29ad.png)

**Comment by collinhover** [comment]
I wouldn't say the pathfinding is wrong, just that it does not know who is using the path, and in most cases it shouldn't care. The right path is always the one that costs the least, and anything beyond that can become expensive for performance or impossible for me to predict. For example, to fix your case, what if I don't allow the pathfinding to go up unless the characters can reach that spot? How do I predict how high your characters can jump, or what if they can double jump, or use a jet pack? So I need to leave the choice in adding that sort of performance heavy path analysis to the individual game dev.

I like your idea for learning, in fact some time ago, I considered adding a system where the pathfinding tries to learn, and a record of paths is kept with their success rate. This is basically similar to what you are describing, and I think it is a great idea, but I've never had the time to implement it. If you want to have a go at it, I'd love to have it in the library :-)

**Comment by arakash92** [comment]
Yeah the path isn't wrong 'period', it's wrong relative to my character class :P
And yea, it makes sense that the pathfinding shouldn't care about AI stuff

Another idea similar to the 'learning' concept is, pre-made paths created in weltmeister via either placing entities or painting on a map. You could then have two types of 'points' to place, waypoints and destinations.

So whenever a character has a target to moveTo, it will check if that target is inside the destination point and then start walking through any of its connected 'paths' designated as waypoints.

**Comment by collinhover** [comment]
Premade paths would certainly make pathfinding cheaper... the pathfinding utility does a lot of precalculation and builds an entire map whenever a new level loads, so perhaps something like this could even be automated. Good idea =)

**Comment by arakash92** [comment]
Right, yea. It could do a 'mass-learn' on load.

Just a quick question.. I have a 'chest' entity which extends ig.Lever. my player has the abilityInteract.
But I'm getting errors when I try to 'open' the chest by standing close to it and running the 'activate' method on the ability.

What am I missing?

**Comment by collinhover** [comment]
To use any ability, you should call the `execute` method. My guess is that the ability doesn't have a target, so either you can set the ability to find one automatically by setting the `canFindTarget` to true, or just pass the chest entity to the ability's `setEntityTarget` method. See the ability example at: https://github.com/collinhover/impactplusplus/blob/master/lib/plusplus/abilities/ability.js#L66

If it still errors, can you open a new issue and post the error + line number + file name please?

**Comment by collinhover** [comment]
You can also check out the docs for abilities: http://collinhover.github.io/impactplusplus/ig.Ability.html, right at the top it has a red warning that may help you solve the issue.

**Comment by arakash92** [comment]
Ah ok. I was calling the wrong method on the ability object. Thanks :)

**Comment by collinhover** [comment]
No prob, it is partially my fault for not making that clear in all the abilities (it is quite easy to look at the interact ability and think the activate method is what you need).

I'm going to close this issue as it has gone off track at this point and most of the original list now has examples.
