### ISSUE TITLE
Function `shapesFromCollisionMap` fails to produce hollow rectangles.

### ISSUE THREAD

**Issue by Joncom** [collinhover/impactplusplus#61]
**Test Case:**

```
// main.js
ig.module('game.main')
.requires(
    'plusplus.helpers.utilstile',
    'impact.game'
)
.defines(function(){
    MyGame = ig.Game.extend({
        init: function() {
            var data = [
                [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
                [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1],
                [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1],
                [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1],
                [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1],
                [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1],
                [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1],
                [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1],
                [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1],
                [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1],
                [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1],
                [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1],
                [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1],
                [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1],
                [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1],
                [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]
            ];
            var tilesize = 8;
            var collisionMap = new ig.CollisionMap(tilesize, data);
            var shapes = ig.utilstile.shapesFromCollisionMap(collisionMap);
            var solids = shapes.solids;
            for(var i=0; i<solids.length; i++) {
                var vertices = solids[i].settings.vertices;
                console.log(JSON.stringify(vertices));
            }
        }
    });
    ig.main( '#canvas', MyGame, 60, 320, 240, 2 );
});
```

**Expected Output:**
4 rectangles (1 top, 1 bottom, 1 left, and 1 right) which altogether form a hollow square.

**Actual Output:**
1 solid square, filled in where it should be hollow ([screenshot](http://puu.sh/4yE7A.png)).

```
[{"x":-56,"y":56},{"x":-56,"y":-56},{"x":56,"y":-56},{"x":56,"y":56}] 
```

**Note:**
This test case was done September 23, 2013 using the current **dev** branch.

**Comment by collinhover** [comment]
This is the correct behavior based on the default options. In most cases, the outer ring of vertices of a collision map will never be used in collisions, so it is discarded. Check out the docs, specifically https://github.com/collinhover/impactplusplus/blob/master/lib/plusplus/helpers/utilstile.js#L147

Did that do it?

**Comment by Joncom** [comment]
No, that didn't do it.

Using:

```
var shapes = ig.utilstile.shapesFromCollisionMap(
                collisionMap, {retainBoundaryOuter:true});
```

The output is now: 

```
[{"x":-64,"y":64},{"x":-64,"y":-64},{"x":64,"y":-64},{"x":64,"y":64}]
[{"x":-56,"y":56},{"x":-56,"y":-56},{"x":56,"y":-56},{"x":56,"y":56}]
```

Which is [two overlapping squares](http://puu.sh/4yGZZ.png), whereas it should look something like [this](http://puu.sh/4yH4J.png) instead.

**Comment by collinhover** [comment]
Ah, okay: https://github.com/collinhover/impactplusplus/blob/master/lib/plusplus/helpers/utilstile.js#L153

**Comment by Joncom** [comment]
Using:

```
{ retainBoundaryOuter: true, rectangles: true }
```

...results in the same two overlapping squares: 

```
[{"x":-64,"y":64},{"x":-64,"y":-64},{"x":64,"y":-64},{"x":64,"y":64}]
[{"x":-56,"y":56},{"x":-56,"y":-56},{"x":56,"y":-56},{"x":56,"y":56}]
```

And using:

```
{ rectangles: true }
```

...results in a single square which still occupies the area that should be clear.

No combination of any mentioned options result in shapes that resembles [a hollow square](http://puu.sh/4yH4J.png).

**Comment by collinhover** [comment]
The result using just rectangles setting appears to be incorrect. I'll take a look at it.

**Comment by collinhover** [comment]
For whatever reason, it seems I decided that solids did not get the rectangles setting. Latest dev works as expected on my end, can you verify?

**Comment by Joncom** [comment]
Works now. Awesome, thank you!! :)
