### ISSUE TITLE
Did the character initiate a jump?

### ISSUE THREAD

**Issue by arakash92** [collinhover/impactplusplus#64]
I have a `player` entity that extends the impact++ `playerEntity` and I need to play a sound when the character initiates a jump.

I couldn't find a way to easily check whether he initiated a jump or not.

The only thing I have is the `jumping` property but that property stays true for the entirety of the jump.

I think the `jump` method on the `playerEntity` class should return `true` or `false` when initiating a jump, such that I can do :

``` javascript
jump: function() {
    if (this.parent()) {
        this.sound.jump.play();
    }
}

```

I have never issued a pull request before though so don't know how to do that :P

**Comment by collinhover** [comment]
Not a bad idea, but you can also just do:

```
jump: function() {
    var wasJumping = this.jumping;
    this.parent();
    if( this.jumping !== wasJumping) {
        this.sound.jump.play();
    }
}
```

I think that in terms of how the library is designed, playing sounds should be handled similarly to how automatic animation switching is handled: after the update, check and play sounds based on the character's status. If you figure out pull requests, I'm always open to improvements!
