### ISSUE TITLE
ig.game.getEntitiesByClass forces area boundary

### ISSUE THREAD

**Issue by racingcow** [collinhover/impactplusplus#68]
Hi, @collinhover. I think I may have discovered a bug, or at least a change in behavior that I don't quite know how to handle yet.

Since the new code on lines [1697](https://github.com/collinhover/impactplusplus/blob/e5cd55a57b69b240874015469b31bc8f7f1cf3e5/lib/plusplus/core/game.js#L1697)-[1705](https://github.com/collinhover/impactplusplus/blob/e5cd55a57b69b240874015469b31bc8f7f1cf3e5/lib/plusplus/core/game.js#L1705) of game.js was introduced in [this commit](https://github.com/collinhover/impactplusplus/commit/e5cd55a57b69b240874015469b31bc8f7f1cf3e5), it looks like the behavior of `ig.game.getEntitiesByClass` has changed.

I used to be able to do something like this to get the first entity of type (class name, not type from plusplus type system) `EntityClaribel`...

``` javascript
var firstMatching = ig.game.getEntitiesByClass('EntityClaribel')[0];
```

...but after the change, it seems that I have to either send in settings for `distanceSquared`/`from`, or `minX`, `minY`, `maxX`, and `maxY`. If I don't, `ig.game.getEntitiesByClass` returns an empty array, and `firstMatching` from the code above is `undefined`.

If I try something like...

``` javascript
var matching = ig.game.getEntitiesByClass('EntityClaribel', { 
    distanceSquared: 100000,
    from: {x: 0, y: 0}
});
var firstMatching = matching[0];
```

... I get the entity I am looking for, but then in my specific case, the camera won't follow the main player (not sure why this happens yet).

Is this a bug, or am I just missing something?

**Comment by collinhover** [comment]
Ah, it is a bug actually, thanks for finding. When I added the distance check, I changed the if statement slightly to require distance or intersect, when those should both be optional. I'll push the fix today.

**Comment by collinhover** [comment]
Okay I've fixed it but am continuing to have internet issues. Once I get a connection, I'll push the fix.
