### ISSUE TITLE
EntityText not working?

### ISSUE THREAD

**Issue by arakash92** [collinhover/impactplusplus#72]
I'm trying to spawn a EntityText using the following but it's not working...

``` javascript
ig.game.spawnEntity(EntityText, x, y, {
    text: 'hello',
});
```

I have tried setting the 'textDisplayed' property too to no avail.

What's going on?

**Comment by arakash92** [comment]
Never mind, I was passing in an int :p
I think the entityText should do .toString() on the text passed in though.

**Comment by collinhover** [comment]
Yep, it should convert the text value to string for safety. Can you make a pull request with the change?

**Comment by arakash92** [comment]
Good idea, let's see if I can do this :P

**Comment by arakash92** [comment]
So, I'll fork the repo. then commit changes to the dev branch? or master?

**Comment by collinhover** [comment]
Dev please!

**Comment by arakash92** [comment]
There, I did a pull request :P
