### ISSUE TITLE
Pixel positioning on linked UI Elements?

### ISSUE THREAD

**Issue by racingcow** [collinhover/impactplusplus#76]
I have a question related to positioning `UIElement`s.

I have a `UIMenu` linked to a `UIHighlight` (both extend `UIElement`),,, 

``` javascript
ig.module(
        'mygame.ui.menu'
    )
    .requires(
        //...
    )
    .defines(function () {
        'use strict';

        ig.UIMenu = ig.global.UIMenu = ig.UIElement.extend({

            //...

            init: function(x, y, settings) {
                this.parent(x, y, settings);

                this.highlight = ig.game.spawnEntity(ig.Highlight, 0, 0, {
                    linkedTo: this,
                    zIndex: this.zIndex + 1,
                    name: 'highlight',
                    //some way to set pos.x/y relative to this.pos?
                });

            },

            //...

        });

    });
```

I want to be able to position `UIHighlight` a precise number of pixels away from `UIMenu`. It looks like once you have the two linked, you have to [position the linked element](https://github.com/collinhover/impactplusplus/blob/f830d14aa7e05d30ccc94f08416ed4d14bda10cc/lib/plusplus/ui/ui-element.js#L289) using percentages and `UIElement.linkAlign`.

Is there some way to set the position of the linked element using pixels? Or is there some other easier way that I am missing?

**Comment by collinhover** [comment]
Use `margin` set to the pixel value with `marginAsPct` set to false: https://github.com/collinhover/impactplusplus/blob/master/lib/plusplus/ui/ui-element.js#L102

**Comment by racingcow** [comment]
Hmm.  `margin` only seems to cause my `UIHighlight` to shift position when I don't set `linkedTo`. When I try this...

``` javascript
ig.module(
        'mygame.ui.menu'
    )
    .requires(
        //...
    )
    .defines(function () {
        'use strict';

        ig.UIMenu = ig.global.UIMenu = ig.UIElement.extend({

            //...

            init: function(x, y, settings) {
                this.parent(x, y, settings);

                this.highlight = ig.game.spawnEntity(ig.Highlight, 0, 0, {
                    linkedTo: this,
                    zIndex: this.zIndex + 1,
                    name: 'highlight',
                    marginAsPct: false,
                    margin: {x: 123, y: 123}
                });

            },

            //...

        });

    });
```

... [`this.margin.x` is 0](https://github.com/collinhover/impactplusplus/blob/f830d14aa7e05d30ccc94f08416ed4d14bda10cc/lib/plusplus/ui/ui-element.js#L310) when the `UIElement.reposition` method is called.

I'll dig into it more tonight and try and reproduce the issue in a small sample app. Hopefully I'll either find something specific in my game that is causing this, or it will give me something to send in that will repro what I am seeing.

**Comment by collinhover** [comment]
I actually use pixel positioning to do the health and energy meters in the SUPER COLLIDER! demo. The health meter is positioned in the screen 15 pixels from the top left, and the energy meter is linked to the health meter and positioned 10 pixels below it.

Health meter
https://github.com/collinhover/impactplusplus/blob/master/examples/supercollider/lib/game/entities/player.js#L274

Energy meter
https://github.com/collinhover/impactplusplus/blob/master/examples/supercollider/lib/game/entities/player.js#L294

Hope this helps!

**Comment by racingcow** [comment]
I think this has something to do with whether or not `UIElement.useLinkAlign` is set to something non-zero on the child element (the one linking to something else). If I specify something like `linkAlign: {x: 1, y: 1}`, I can use negative values on the `margin` to position the highlight where I want it. If I leave it at the default zero vector, however, my highlight element shows up in the center of the entity to which it is linked, regardless of what I specify for the margin.

I have [a sample app](https://github.com/racingcow/impactplusplus-sample-76) that will reproduce the behavior. You should be able to add impactjs and plusplus to the `lib` folder and get it to work. It is setup so that if you hit the `ESC` key, `linkAlign` is zero, and it always positions in the center. If you hit `TAB`, it will specify `linkAlign`, and will position the highlight element in the correct position.

If you have time, could you take a look at it? I can work with what I know now if I need to, but it is a bit more cumbersome to calculate from the bottom-right of the entity. 

It would be great if there were some way to use `linkAlign` to make the coordinates for the "child" element be relative to the upper-left of the "parent" element. It would seem like either `linkAlign: {x: 0, y: 0}` or `linkAlign: {x: -1, y: -1}` should work, but the former prevents the `margin` property from working, and the latter seems to give some position that isn't in the upper-left corner.

Maybe there is something that I am missing still that would make this easier?

Thanks for all your help!

**Comment by collinhover** [comment]
Linked elements should align to the center by default, and `linkAlign: {x: -1, y: -1}` should get them to the top left much as `linkAlign: {x: 1, y: 1}` gets them to the bottom right. It sounds like this is not happening, so there is probably a bug. I'm looking into it, thanks for providing a sample.

**Comment by collinhover** [comment]
Tried out the sample, setting `linkAlign: {x: -1, y: -1}` with `margin: {x: 0, y: 0}` does place the element in the top left corner, minus its own width/height, so that the bottom right corner of the linked element touches the top left of the linkedTo element. This is the behavior I'd expect.

What you're looking for is that the `linkAlign` property be relative to the inside of the linkedTo element, so that when you use `linkAlign: {x: -1, y: -1}`, the linking element's top left corner is touching the linkedTo element's top left corner, correct?

**Comment by racingcow** [comment]
Ah, I see. Yeah, it was just me going off of assumptions/past experience, but I guess I had originally expected it to work as you describe, such that the linked coordinate system is relative to the top-left of the linkedTo element. That way, if I had set `linkAlign: {x: -1, y: -1}`, it would make it a bit easier to place the linking element over the fixed positions on the linkedTo element (x would be positive toward the right of the screen instead of negative, there wouldn't be as much of a need to factor in the size of the linking element, etc.).

I don't mind working with it the way it is now if you think it makes sense in most linking scenarios for ui elements. Perhaps something simpler such as a bit more explanation on the documentation for `linkAlign` and/or `margin` properties would work?

**Comment by collinhover** [comment]
The way it is now is setup for elements that will be positioned next to each other. I think we could add a property to the ui elements that flips the link align to be relative to the inside of the linked to element for situations like yours. Would you mind adding this and make a pull request? Everything that needs to change is in the ui element class's positioning methods.

**Comment by racingcow** [comment]
Sure, I'll give the PR a shot. Hopefully I can get it done either tonight or tomorrow night.
