### ISSUE TITLE
Event system?

### ISSUE THREAD

**Issue by arakash92** [collinhover/impactplusplus#82]
So I'm writing a more complex AI system than I previously had.

I saw some stuff in the ++ code about 'signals'?
Is this an event system?

Anyway, what I want is to 'listen' or 'bind' to the ig.Character.moveToComplete method without overriding the method.

Is there a way to do so, and if not. I might look into writing an event system.. actually I think I already have a JS event system which I can hook into ++ easily.

**Comment by collinhover** [comment]
Yes signals are used as an event system, based on http://millermedeiros.github.io/js-signals/ (you can use those docs too).

When an entity completes a move to and `movingToOnce` is true for that move to, it dispatches the `onMovedTo` signal: https://github.com/collinhover/impactplusplus/blob/master/lib/plusplus/core/entity.js#L3699

Here is the signals code: https://github.com/collinhover/impactplusplus/blob/master/lib/plusplus/helpers/signals.js
