### ISSUE TITLE
EntityExtended.movedTo

### ISSUE THREAD

**Issue by arakash92** [collinhover/impactplusplus#85]
The docs say this about the `movedTo` property: "Whether entity has moved to currently moving to entity." what does it mean? and.. why is it not true when my entity has completed moving to an entity?

**Comment by arakash92** [comment]
I checked the code in EntityExtended and it seems when you moveTo with 'once' set to true, when it's done moving. the movedTo property is actually set to false...

Is this a bug?

**Comment by collinhover** [comment]
You're going to need to give me more context on the entity that is moving. Is it a character? Is it using pathfinding or just instant move? Etc

If once is setting the movedTo to false, that is probably a bug. Can you link the line number please?

**Comment by arakash92** [comment]
3724 of ig.EntityExtended

The call order is moveTo() > moveToComplete() > moveToStop.

To fix it, add `this.movedTo = true;` right underneath line 3698.

**Comment by collinhover** [comment]
I see, yes this is a bug when once is true. I'll add your fix, thanks :-)

**Comment by arakash92** [comment]
np! :)

**Comment by collinhover** [comment]
This is fixed now, and the `onMovedTo` signal is now always dispatched when a move to is completed, instead of only when moving to once.
