### ISSUE TITLE
howler.js

### ISSUE THREAD

**Issue by racingcow** [collinhover/impactplusplus#87]
Hello, everyone.

I noticed that @bdaenen and @afflicto have been working on [audio improvements to the game](https://github.com/collinhover/impactplusplus/issues/77). Would support for/use of something like [howler.js](https://github.com/goldfire/howler.js) help with cross-browser support? 

I don't know a lot about Web Audio API yet, but howler.js will fall back to vanilla HTML5 audio support when Web Audio is not available. Maybe it would help provide support for some of the more advanced features of Web Audio (like panning/directional sound) for newer browsers, while allowing for graceful degradation on [some of the browsers](http://caniuse.com/audio-api) that don't yet support Web Audio?

It supports some other interesting features as well, like "audio sprites", and seems to be getting [fairly popular](https://hacks.mozilla.org/2013/02/simplifying-audio-in-the-browser/).

I just thought I'd throw it out there as something to consider.

**Comment by collinhover** [comment]
Not a bad idea, but can you post this in reply to #77 so we can keep the discussion in one location?
