### ISSUE TITLE
"Patrolling" Character?

### ISSUE THREAD

**Issue by arakash92** [collinhover/impactplusplus#89]
I'm trying to implement a patrolling character but it's never working as I expect it.

Sometimes when I call entity.moveTo(targetEntity).. he won't move at all, why?

**Comment by collinhover** [comment]
Seems like maybe you got this working, but you should really try to use the `ig.Creature` abstract if you are not already. You can tell a creature to wander using `canWanderX` (and for top down games or flying creatures `canWanderY` also), and it will patrol back and forward from one edge to another. Or you can give it a tether and it will patrol `tetherDistance` away from the tether, then walk back to the tether, and do it again in the other direction.

**Comment by arakash92** [comment]
Huh, I never thought about the `ig.Creature` class, I'm just using the Character haha.

Anyway, there was a bug in my own code which was calling moveTo multiple places.
