### ISSUE TITLE
handleMovementTrace on slopes?

### ISSUE THREAD

**Issue by arakash92** [collinhover/impactplusplus#93]
It seems that when my projectile hits slopes, the handleMovementTrace isn't called?

**Comment by collinhover** [comment]
`handleMovementTrace` is always called on dynamic entities, whether they are hitting the map or not. I'm not sure I understand your question, do you mean something else is not being called?

**Comment by arakash92** [comment]
Projectiles don't seem to collide/die when hitting slopes. They slide along slopes.

**Comment by collinhover** [comment]
Can't reproduce this with any slope on my end. You're setting the `collisionSticky` and/or `collisionKills` right? Can you post your projectile code?

**Comment by arakash92** [comment]
I don't remember how, but I sorted it. I believe it was an issue on my end.
