### ISSUE TITLE
My enemies melee each other?

### ISSUE THREAD

**Issue by arakash92** [collinhover/impactplusplus#95]
So I have multiple enemies that are in the group 'enemy' and they have a 'melee' ability and they are able to attack each other.

I tried the following but it didn't work:

``` javascript
this.melee = new ig.AbilityMelee(this);

//set targetable group and type
ig.utils.addType(ig.EntityExtended, this.melee, 'typeTargetable', 'DAMAGEABLE');
ig.utils.addType(ig.EntityExtended, this.melee, 'groupTargetable', 'FRIEND', 'GROUP');
```

What am I missing?

**Comment by collinhover** [comment]
Using the latest dev branch? There was a small issue with ability targeting that was allowing same groups to be targeted, but it should be fixed.

**Comment by arakash92** [comment]
I'm not sure if I am or not but I removed the 'typeTargetable' (first line) and just used the 'groupTargetable'.
